import unicodedata as ud, json
S={
"straight":[
("|","absolute value / magnitude |x|; divides (a|b); conditional probability P(A|B); logical OR / pipe in code; set-builder 'such that'"),
("/","division and fractions; ratio and rate (km/h); path separator; 'per' and alternatives (and/or); quotient structure G/H"),
("\\","set difference A\\B; escape character in code; left division in linear algebra (A\\b); path separator on Windows"),
("_","subscript marker in typesetting; blank or placeholder; underscore in names (snake_case); 'unused value' in code"),
("-","subtraction; negation (−x); range (1-5); hyphen joining words; set difference in some notations"),
("+","addition; positive sign; union or disjoint sum; 'and more' (18+); string concatenation in code"),
("=","equality; assignment in code; definition (with :=); equation balance"),
("≠","not equal; inequality of values"),
("<","less than; strict order; generic type brackets in code; 'is a subgroup of' (H < G)"),
(">","greater than; strict order; redirect in shells; quotation marker in messages"),
("≤","less than or equal; partial order"),
("≥","greater than or equal; partial order"),
("^","exponent in plain text (x^2); logical AND in some plain-text notations; XOR in code; caret insertion mark"),
("[","closed interval [a,b]; matrix and list delimiter; index or subscript access a[i]; commutator [A,B] (opening)"),
("]","closing pair of ["),
("#","number or count (#items); cardinality; comment marker in Python; pound / hash"),
("*","multiplication in code; convolution (f*g); footnote marker; wildcard; Kleene star (repetition)"),
("×","multiplication; cross product (a×b); Cartesian product (A×B); dimensions (3×4)"),
("±","plus or minus; uncertainty (5 ± 0.1); both roots of an equation"),
("⊥","perpendicular; false or contradiction in logic; independence in probability"),
("∥","parallel; norm ‖x‖ (doubled); parallel composition"),
("∠","angle"),
("△","triangle; symmetric difference (A△B)"),
("□","necessity (modal logic 'it must be'); end of proof (∎ variant); square"),
("∧","logical AND; meet (lattice); wedge product"),
("∨","logical OR; join (lattice)"),
("¬","logical NOT; negation"),
("→","implies; maps to (f: A → B); tends to (x → 0); reaction yields"),
("⇒","logical implication; therefore"),
("⇔","if and only if; logical equivalence"),
("↑","increasing; up arrow notation (Knuth); exponent"),
("Σ","summation (∑); Greek sigma; standard deviation (σ, lowercase)"),
("Δ","change or difference (Δx); discriminant; Laplacian; triangle"),
("∇","gradient, divergence, curl (nabla); del operator"),
("√","square root; radical; nth root with index"),
("∀","for all (universal quantifier)"),
("⊤","true (top) in logic; transpose (Aᵀ)"),
("⊢","proves / entails syntactically (Γ ⊢ φ)"),
],
"curved":[
("0","zero; additive identity; origin (0,0); false (0) in Boolean; placeholder in positional numbers"),
("§","section (legal and textual); in the DSL: presence (glove), a presentiated instance"),
("°","degree of angle; degree of temperature; degree of a vertex or polynomial (in words)"),
("∞","infinity; unbounded limit; lemniscate"),
(":","ratio (a:b); 'such that' in set-builder; type annotation in code (x: int); definition (:=); proportion (::)"),
("(","grouping; function application f(x); open interval (a,b); ordered pair or tuple (opening)"),
(")","closing pair of ("),
("{","set delimiter {a,b}; block in code; piecewise definition (opening)"),
("}","closing pair of {"),
(".","decimal point; multiplication (a·b, raised); end of statement; member access obj.attr"),
(",","separator in lists and coordinates; decimal comma in many countries; thousands separator"),
("'","prime (f′, derivative); feet and minutes; apostrophe; string quote in code"),
("~","approximately; similar to; negation in some logics; 'is distributed as' (X ~ N(0,1))"),
("∘","function composition (f∘g); ring operator; Hadamard product in some texts"),
("○","circle; empty or open marker"),
("∫","integral; area under a curve; accumulation"),
("∮","contour (closed path) integral"),
("∂","partial derivative; boundary of a set (∂A)"),
("⊂","proper subset"),
("⊃","superset; material implication (older logic)"),
("∪","union of sets"),
("∩","intersection of sets"),
("≈","approximately equal; in the DSL: a glyph's field of meaning"),
("∼","similar to; asymptotic to; equivalence relation"),
("∴","therefore"),
("∵","because"),
("ε","small quantity; element of (∈, original form); empty string in formal languages"),
],
"hybrid":[
("%","percent (per hundred); modulo in code (7 % 3); in the DSL: inversion (alg-00%)"),
("$","dollar and currency; variable marker in shells; end of line in regular expressions; math mode in LaTeX"),
(";","separator stronger than a comma; end of statement in many languages; sequential composition"),
("…","ellipsis: continuation of a pattern (1, 2, …, n); omission"),
("&","and; logical AND in code (&&); reference/address in some languages"),
("@","at; decorator in Python; matrix multiplication operator (A @ B)"),
("?","unknown or question; conditional operator (c ? a : b); optional (zero or one) in regular expressions"),
("!","factorial (n!); logical NOT in code; emphasis; uniqueness (∃!)"),
("÷","division (obelus)"),
("‰","per mille (per thousand)"),
("₪","new shekel (currency); historically a unit of weight"),
("π","pi ≈ 3.14159; product (Π, uppercase); projection"),
("∈","element of (x ∈ A)"),
("∉","not an element of"),
("∅","empty set"),
("∝","proportional to"),
("⊕","direct sum; exclusive OR (XOR); circled plus"),
("⊗","tensor product; circled times"),
("¶","paragraph (pilcrow)"),
("¢","cent"),
("€","euro"),
("£","pound sterling"),
("ℵ","aleph: cardinality of infinite sets (ℵ₀)"),
("ℏ","reduced Planck constant (h-bar)"),
("Ω","ohm (resistance); sample space; last of a sequence"),
]}
out={}
for k,lst in S.items():
    out[k]=[{"sym":s,"cp":"U+%04X"%ord(s) if len(s)==1 else "",
             "name":ud.name(s,"") if len(s)==1 else "","cat":ud.category(s) if len(s)==1 else "",
             "mirrored":bool(ud.mirrored(s)) if len(s)==1 else False,"uses":[u.strip() for u in t.split(";")]} for s,t in lst]
json.dump(out,open('/tmp/symbols.json','w'),ensure_ascii=False)
print({k:len(v) for k,v in out.items()}, out['straight'][0])
