KEYBOARDS = {
    "Straight": ["|", "/", "\\", "_", "-", "+", "=", "≠", "<", ">", "≤", "≥", "^", "[", "]", "#", "*", "×", "±", "⊥", "∥", "∠", "△", "□", "∧", "∨", "¬", "→", "⇒", "⇔", "↑", "Σ", "Δ", "∇", "√", "∀", "⊤", "⊢"],
    "Curved": ["0", "§", "°", "∞", ":", "(", ")", "{", "}", ".", ",", "'", "~", "∘", "○", "∫", "∮", "∂", "⊂", "⊃", "∪", "∩", "≈", "∼", "∴", "∵", "ε"],
    "Hybrid": ["%", "$", ";", "…", "&", "@", "?", "!", "÷", "‰", "₪", "π", "∈", "∉", "∅", "∝", "⊕", "⊗", "¶", "¢", "€", "£", "ℵ", "ℏ", "Ω"],
    "DSL": ["%", "-%", "§", "≈", ":-", "→", "/", "=", "=T", "=F", "|", "::", ":", "∴", "₪", "‰", "__י__", "|x|", "||", "__", "_", "[", "]", "{", "}", "(", ")", "<", ">", "#", "°", "√", "+", "-", "…", "§ר§"],
    "Brackets": ["(", ")", "[", "]", "{", "}", "⟨", "⟩", "⟦", "⟧", "⟪", "⟫", "⌈", "⌉", "⌊", "⌋", "⦃", "⦄", "⦅", "⦆", "⦇", "⦈", "⦉", "⦊", "⦋", "⦌", "⦍", "⦎", "⦏", "⦐", "⦑", "⦒", "⦓", "⦔", "⦕", "⦖", "⦗", "⦘", "⁅", "⁆", "〈", "〉", "《", "》", "「", "」", "『", "』", "【", "】", "〔", "〕", "〖", "〗", "〘", "〙", "〚", "〛", "‹", "›", "«", "»"],
    "Math": ["+", "−", "×", "÷", "±", "∓", "·", "∘", "∙", "=", "≠", "≈", "≃", "≅", "≡", "≢", "∼", "∝", "<", ">", "≤", "≥", "≪", "≫", "√", "∛", "∜", "∞", "∑", "∏", "∐", "∫", "∬", "∭", "∮", "∂", "∇", "∆", "∈", "∉", "∋", "∌", "⊂", "⊃", "⊆", "⊇", "⊄", "⊅", "∪", "∩", "∖", "∅", "∀", "∃", "∄", "∧", "∨", "¬", "⊻", "⊼", "⊽", "⊕", "⊖", "⊗", "⊘", "⊙", "⊢", "⊣", "⊤", "⊥", "⊨", "∴", "∵", "∶", "∷", "′", "″", "‴", "ℵ", "ℶ", "ℏ", "ℓ", "℘", "ℜ", "ℑ", "∠", "∡", "∢", "⊾", "△", "▽", "⟂", "∥", "∦"],
    "Arrows": ["←", "↑", "→", "↓", "↔", "↕", "↖", "↗", "↘", "↙", "↚", "↛", "↜", "↝", "↞", "↟", "↠", "↡", "↢", "↣", "↤", "↥", "↦", "↧", "↨", "↩", "↪", "↫", "↬", "↭", "↮", "↯", "↰", "↱", "↲", "↳", "↴", "↵", "↶", "↷", "↺", "↻", "↼", "↽", "↾", "↿", "⇀", "⇁", "⇂", "⇃", "⇄", "⇅", "⇆", "⇇", "⇈", "⇉", "⇊", "⇋", "⇌", "⇍", "⇎", "⇏", "⇐", "⇑", "⇒", "⇓", "⇔", "⇕", "⇖", "⇗", "⇘", "⇙", "⇚", "⇛", "⟵", "⟶", "⟷", "⟸", "⟹", "⟺", "⟼", "⤴", "⤵"],
    "Box": ["─", "━", "│", "┃", "┄", "┅", "┆", "┇", "┈", "┉", "┊", "┋", "┌", "┐", "└", "┘", "├", "┤", "┬", "┴", "┼", "═", "║", "╒", "╓", "╔", "╕", "╖", "╗", "╘", "╙", "╚", "╛", "╜", "╝", "╞", "╟", "╠", "╡", "╢", "╣", "╤", "╥", "╦", "╧", "╨", "╩", "╪", "╫", "╬", "╭", "╮", "╯", "╰", "╱", "╲", "╳", "╴", "╵", "╶", "╷", "▀", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█", "▉", "▊", "▋", "▌", "▍", "▎", "▏", "▐", "░", "▒", "▓", "▔", "▕", "■", "□", "▪", "▫", "▬", "▭", "▮", "▯", "▲", "△", "▶", "▷", "▼", "▽", "◀", "◁", "◆", "◇", "○", "◎", "●", "◐", "◑", "◒", "◓", "◯"],
    "Hebrew": ["א", "ב", "ג", "ד", "ה", "ו", "ז", "ח", "ט", "י", "כ", "ל", "מ", "נ", "ס", "ע", "פ", "צ", "ק", "ר", "ש", "ת", "ך", "ם", "ן", "ף", "ץ", "ים", "יה", "אמש"],
    "Greek": ["α", "β", "γ", "δ", "ε", "ζ", "η", "θ", "ι", "κ", "λ", "μ", "ν", "ξ", "ο", "π", "ρ", "σ", "τ", "υ", "φ", "χ", "ψ", "ω", "Γ", "Δ", "Θ", "Λ", "Ξ", "Π", "Σ", "Φ", "Ψ", "Ω"],
    "Numbers": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "⁰", "¹", "²", "³", "⁴", "⁵", "⁶", "⁷", "⁸", "⁹", "₀", "₁", "₂", "₃", "₄", "₅", "₆", "₇", "₈", "₉", "½", "⅓", "⅔", "¼", "¾", "⅛", "ⅰ", "ⅱ", "ⅲ", "ⅳ", "ⅴ", "ⅵ", "ⅶ", "ⅷ", "ⅸ", "ⅹ", "∞", "#"],
    "Marks": [".", ",", ":", ";", "!", "?", "'", "\"", "`", "~", "^", "*", "&", "@", "$", "¢", "€", "£", "¥", "₪", "§", "¶", "†", "‡", "•", "‣", "◦", "‰", "‱", "°", "′", "″", "№", "℗", "©", "®", "™"],
}

USES = {
    "|": ["absolute value / magnitude |x|", "divides (a|b)", "conditional probability P(A|B)", "logical OR / pipe in code", "set-builder 'such that'"],
    "/": ["division and fractions", "ratio and rate (km/h)", "path separator", "'per' and alternatives (and/or)", "quotient structure G/H"],
    "\\": ["set difference A\\B", "escape character in code", "left division in linear algebra (A\\b)", "path separator on Windows"],
    "_": ["subscript marker in typesetting", "blank or placeholder", "underscore in names (snake_case)", "'unused value' in code"],
    "-": ["subtraction", "negation (−x)", "range (1-5)", "hyphen joining words", "set difference in some notations"],
    "+": ["addition", "positive sign", "union or disjoint sum", "'and more' (18+)", "string concatenation in code"],
    "=": ["equality", "assignment in code", "definition (with :=)", "equation balance"],
    "≠": ["not equal", "inequality of values"],
    "<": ["less than", "strict order", "generic type brackets in code", "'is a subgroup of' (H < G)"],
    ">": ["greater than", "strict order", "redirect in shells", "quotation marker in messages"],
    "≤": ["less than or equal", "partial order"],
    "≥": ["greater than or equal", "partial order"],
    "^": ["exponent in plain text (x^2)", "logical AND in some plain-text notations", "XOR in code", "caret insertion mark"],
    "[": ["closed interval [a,b]", "matrix and list delimiter", "index or subscript access a[i]", "commutator [A,B] (opening)"],
    "]": ["closing pair of ["],
    "#": ["number or count (#items)", "cardinality", "comment marker in Python", "pound / hash"],
    "*": ["multiplication in code", "convolution (f*g)", "footnote marker", "wildcard", "Kleene star (repetition)"],
    "×": ["multiplication", "cross product (a×b)", "Cartesian product (A×B)", "dimensions (3×4)"],
    "±": ["plus or minus", "uncertainty (5 ± 0.1)", "both roots of an equation"],
    "⊥": ["perpendicular", "false or contradiction in logic", "independence in probability"],
    "∥": ["parallel", "norm ‖x‖ (doubled)", "parallel composition"],
    "∠": ["angle"],
    "△": ["triangle", "symmetric difference (A△B)"],
    "□": ["necessity (modal logic 'it must be')", "end of proof (∎ variant)", "square"],
    "∧": ["logical AND", "meet (lattice)", "wedge product"],
    "∨": ["logical OR", "join (lattice)"],
    "¬": ["logical NOT", "negation"],
    "→": ["implies", "maps to (f: A → B)", "tends to (x → 0)", "reaction yields"],
    "⇒": ["logical implication", "therefore"],
    "⇔": ["if and only if", "logical equivalence"],
    "↑": ["increasing", "up arrow notation (Knuth)", "exponent"],
    "Σ": ["summation (∑)", "Greek sigma", "standard deviation (σ, lowercase)"],
    "Δ": ["change or difference (Δx)", "discriminant", "Laplacian", "triangle"],
    "∇": ["gradient, divergence, curl (nabla)", "del operator"],
    "√": ["square root", "radical", "nth root with index"],
    "∀": ["for all (universal quantifier)"],
    "⊤": ["true (top) in logic", "transpose (Aᵀ)"],
    "⊢": ["proves / entails syntactically (Γ ⊢ φ)"],
    "0": ["zero", "additive identity", "origin (0,0)", "false (0) in Boolean", "placeholder in positional numbers"],
    "§": ["section (legal and textual)", "in the DSL: presence (glove), a presentiated instance"],
    "°": ["degree of angle", "degree of temperature", "degree of a vertex or polynomial (in words)"],
    "∞": ["infinity", "unbounded limit", "lemniscate"],
    ":": ["ratio (a:b)", "'such that' in set-builder", "type annotation in code (x: int)", "definition (:=)", "proportion (::)"],
    "(": ["grouping", "function application f(x)", "open interval (a,b)", "ordered pair or tuple (opening)"],
    ")": ["closing pair of ("],
    "{": ["set delimiter {a,b}", "block in code", "piecewise definition (opening)"],
    "}": ["closing pair of {"],
    ".": ["decimal point", "multiplication (a·b, raised)", "end of statement", "member access obj.attr"],
    ",": ["separator in lists and coordinates", "decimal comma in many countries", "thousands separator"],
    "'": ["prime (f′, derivative)", "feet and minutes", "apostrophe", "string quote in code"],
    "~": ["approximately", "similar to", "negation in some logics", "'is distributed as' (X ~ N(0,1))"],
    "∘": ["function composition (f∘g)", "ring operator", "Hadamard product in some texts"],
    "○": ["circle", "empty or open marker"],
    "∫": ["integral", "area under a curve", "accumulation"],
    "∮": ["contour (closed path) integral"],
    "∂": ["partial derivative", "boundary of a set (∂A)"],
    "⊂": ["proper subset"],
    "⊃": ["superset", "material implication (older logic)"],
    "∪": ["union of sets"],
    "∩": ["intersection of sets"],
    "≈": ["approximately equal", "in the DSL: a glyph's field of meaning"],
    "∼": ["similar to", "asymptotic to", "equivalence relation"],
    "∴": ["therefore"],
    "∵": ["because"],
    "ε": ["small quantity", "element of (∈, original form)", "empty string in formal languages"],
    "%": ["percent (per hundred)", "modulo in code (7 % 3)", "in the DSL: inversion (alg-00%)"],
    "$": ["dollar and currency", "variable marker in shells", "end of line in regular expressions", "math mode in LaTeX"],
    ";": ["separator stronger than a comma", "end of statement in many languages", "sequential composition"],
    "…": ["ellipsis: continuation of a pattern (1, 2, …, n)", "omission"],
    "&": ["and", "logical AND in code (&&)", "reference/address in some languages"],
    "@": ["at", "decorator in Python", "matrix multiplication operator (A @ B)"],
    "?": ["unknown or question", "conditional operator (c ? a : b)", "optional (zero or one) in regular expressions"],
    "!": ["factorial (n!)", "logical NOT in code", "emphasis", "uniqueness (∃!)"],
    "÷": ["division (obelus)"],
    "‰": ["per mille (per thousand)"],
    "₪": ["new shekel (currency)", "historically a unit of weight"],
    "π": ["pi ≈ 3.14159", "product (Π, uppercase)", "projection"],
    "∈": ["element of (x ∈ A)"],
    "∉": ["not an element of"],
    "∅": ["empty set"],
    "∝": ["proportional to"],
    "⊕": ["direct sum", "exclusive OR (XOR)", "circled plus"],
    "⊗": ["tensor product", "circled times"],
    "¶": ["paragraph (pilcrow)"],
    "¢": ["cent"],
    "€": ["euro"],
    "£": ["pound sterling"],
    "ℵ": ["aleph: cardinality of infinite sets (ℵ₀)"],
    "ℏ": ["reduced Planck constant (h-bar)"],
    "Ω": ["ohm (resistance)", "sample space", "last of a sequence"],
    "-%": ["lift: step back up one level"],
    ":-": ["opens the relation in a lateral strand: W = a Genus :- Relation - Objects"],
    "=T": ["true: a gate's condition holds"],
    "=F": ["false: a gate's condition fails"],
    "::": ["proportion: this:that::these:those"],
    "__י__": ["init: the seed that opens a sequence"],
    "|x|": ["the absolute: a bounded term, the nesting frame of an analogy"],
    "||": ["a bar divided into two: both sides of an absolute"],
    "__": ["an empty slot"],
    "§ר§": ["Echo present on both faces: the Matrixed File of ר"],
    "⟨": ["mathematical left angle bracket", "opens a group, pairs with its mirror"],
    "⟩": ["mathematical right angle bracket", "closes a group, pairs with its mirror"],
    "⟦": ["mathematical left white square bracket", "opens a group, pairs with its mirror"],
    "⟧": ["mathematical right white square bracket", "closes a group, pairs with its mirror"],
    "⟪": ["mathematical left double angle bracket", "opens a group, pairs with its mirror"],
    "⟫": ["mathematical right double angle bracket", "closes a group, pairs with its mirror"],
    "⌈": ["left ceiling", "opens a group, pairs with its mirror"],
    "⌉": ["right ceiling", "closes a group, pairs with its mirror"],
    "⌊": ["left floor", "opens a group, pairs with its mirror"],
    "⌋": ["right floor", "closes a group, pairs with its mirror"],
    "⦃": ["left white curly bracket", "opens a group, pairs with its mirror"],
    "⦄": ["right white curly bracket", "closes a group, pairs with its mirror"],
    "⦅": ["left white parenthesis", "opens a group, pairs with its mirror"],
    "⦆": ["right white parenthesis", "closes a group, pairs with its mirror"],
    "⦇": ["z notation left image bracket", "opens a group, pairs with its mirror"],
    "⦈": ["z notation right image bracket", "closes a group, pairs with its mirror"],
    "⦉": ["z notation left binding bracket", "opens a group, pairs with its mirror"],
    "⦊": ["z notation right binding bracket", "closes a group, pairs with its mirror"],
    "⦋": ["left square bracket with underbar", "opens a group, pairs with its mirror"],
    "⦌": ["right square bracket with underbar", "closes a group, pairs with its mirror"],
    "⦍": ["left square bracket with tick in top corner", "opens a group, pairs with its mirror"],
    "⦎": ["right square bracket with tick in bottom corner", "closes a group, pairs with its mirror"],
    "⦏": ["left square bracket with tick in bottom corner", "opens a group, pairs with its mirror"],
    "⦐": ["right square bracket with tick in top corner", "closes a group, pairs with its mirror"],
    "⦑": ["left angle bracket with dot", "opens a group, pairs with its mirror"],
    "⦒": ["right angle bracket with dot", "closes a group, pairs with its mirror"],
    "⦓": ["left arc less-than bracket", "opens a group, pairs with its mirror"],
    "⦔": ["right arc greater-than bracket", "closes a group, pairs with its mirror"],
    "⦕": ["double left arc greater-than bracket", "opens a group, pairs with its mirror"],
    "⦖": ["double right arc less-than bracket", "closes a group, pairs with its mirror"],
    "⦗": ["left black tortoise shell bracket", "opens a group, pairs with its mirror"],
    "⦘": ["right black tortoise shell bracket", "closes a group, pairs with its mirror"],
    "⁅": ["left square bracket with quill", "opens a group, pairs with its mirror"],
    "⁆": ["right square bracket with quill", "closes a group, pairs with its mirror"],
    "〈": ["left angle bracket", "opens a group, pairs with its mirror"],
    "〉": ["right angle bracket", "closes a group, pairs with its mirror"],
    "《": ["left double angle bracket", "opens a group, pairs with its mirror"],
    "》": ["right double angle bracket", "closes a group, pairs with its mirror"],
    "「": ["left corner bracket", "opens a group, pairs with its mirror"],
    "」": ["right corner bracket", "closes a group, pairs with its mirror"],
    "『": ["left white corner bracket", "opens a group, pairs with its mirror"],
    "』": ["right white corner bracket", "closes a group, pairs with its mirror"],
    "【": ["left black lenticular bracket", "opens a group, pairs with its mirror"],
    "】": ["right black lenticular bracket", "closes a group, pairs with its mirror"],
    "〔": ["left tortoise shell bracket", "opens a group, pairs with its mirror"],
    "〕": ["right tortoise shell bracket", "closes a group, pairs with its mirror"],
    "〖": ["left white lenticular bracket", "opens a group, pairs with its mirror"],
    "〗": ["right white lenticular bracket", "closes a group, pairs with its mirror"],
    "〘": ["left white tortoise shell bracket", "opens a group, pairs with its mirror"],
    "〙": ["right white tortoise shell bracket", "closes a group, pairs with its mirror"],
    "〚": ["left white square bracket", "opens a group, pairs with its mirror"],
    "〛": ["right white square bracket", "closes a group, pairs with its mirror"],
    "‹": ["single left-pointing angle quotation mark", "opens a group, pairs with its mirror"],
    "›": ["single right-pointing angle quotation mark", "closes a group, pairs with its mirror"],
    "«": ["left-pointing double angle quotation mark", "opens a group, pairs with its mirror"],
    "»": ["right-pointing double angle quotation mark", "closes a group, pairs with its mirror"],
    "−": ["minus sign"],
    "∓": ["minus-or-plus sign"],
    "·": ["middle dot"],
    "∙": ["bullet operator"],
    "≃": ["asymptotically equal to"],
    "≅": ["approximately equal to"],
    "≡": ["identical to"],
    "≢": ["not identical to"],
    "≪": ["much less-than"],
    "≫": ["much greater-than"],
    "∛": ["cube root"],
    "∜": ["fourth root"],
    "∑": ["n-ary summation"],
    "∏": ["n-ary product"],
    "∐": ["n-ary coproduct"],
    "∬": ["double integral"],
    "∭": ["triple integral"],
    "∆": ["increment"],
    "∋": ["contains as member"],
    "∌": ["does not contain as member"],
    "⊆": ["subset of or equal to"],
    "⊇": ["superset of or equal to"],
    "⊄": ["not a subset of"],
    "⊅": ["not a superset of"],
    "∖": ["set minus"],
    "∃": ["there exists"],
    "∄": ["there does not exist"],
    "⊻": ["xor"],
    "⊼": ["nand"],
    "⊽": ["nor"],
    "⊖": ["circled minus"],
    "⊘": ["circled division slash"],
    "⊙": ["circled dot operator"],
    "⊣": ["left tack"],
    "⊨": ["true"],
    "∶": ["ratio"],
    "∷": ["proportion"],
    "′": ["prime"],
    "″": ["double prime"],
    "‴": ["triple prime"],
    "ℶ": ["bet symbol"],
    "ℓ": ["script small l"],
    "℘": ["script capital p"],
    "ℜ": ["black-letter capital r"],
    "ℑ": ["black-letter capital i"],
    "∡": ["measured angle"],
    "∢": ["spherical angle"],
    "⊾": ["right angle with arc"],
    "▽": ["white down-pointing triangle"],
    "⟂": ["perpendicular"],
    "∦": ["not parallel to"],
    "←": ["leftwards arrow", "direction, mapping, implication or flow"],
    "↓": ["downwards arrow", "direction, mapping, implication or flow"],
    "↔": ["left right arrow", "direction, mapping, implication or flow"],
    "↕": ["up down arrow", "direction, mapping, implication or flow"],
    "↖": ["north west arrow", "direction, mapping, implication or flow"],
    "↗": ["north east arrow", "direction, mapping, implication or flow"],
    "↘": ["south east arrow", "direction, mapping, implication or flow"],
    "↙": ["south west arrow", "direction, mapping, implication or flow"],
    "↚": ["leftwards arrow with stroke", "direction, mapping, implication or flow"],
    "↛": ["rightwards arrow with stroke", "direction, mapping, implication or flow"],
    "↜": ["leftwards wave arrow", "direction, mapping, implication or flow"],
    "↝": ["rightwards wave arrow", "direction, mapping, implication or flow"],
    "↞": ["leftwards two headed arrow", "direction, mapping, implication or flow"],
    "↟": ["upwards two headed arrow", "direction, mapping, implication or flow"],
    "↠": ["rightwards two headed arrow", "direction, mapping, implication or flow"],
    "↡": ["downwards two headed arrow", "direction, mapping, implication or flow"],
    "↢": ["leftwards arrow with tail", "direction, mapping, implication or flow"],
    "↣": ["rightwards arrow with tail", "direction, mapping, implication or flow"],
    "↤": ["leftwards arrow from bar", "direction, mapping, implication or flow"],
    "↥": ["upwards arrow from bar", "direction, mapping, implication or flow"],
    "↦": ["rightwards arrow from bar", "direction, mapping, implication or flow"],
    "↧": ["downwards arrow from bar", "direction, mapping, implication or flow"],
    "↨": ["up down arrow with base", "direction, mapping, implication or flow"],
    "↩": ["leftwards arrow with hook", "direction, mapping, implication or flow"],
    "↪": ["rightwards arrow with hook", "direction, mapping, implication or flow"],
    "↫": ["leftwards arrow with loop", "direction, mapping, implication or flow"],
    "↬": ["rightwards arrow with loop", "direction, mapping, implication or flow"],
    "↭": ["left right wave arrow", "direction, mapping, implication or flow"],
    "↮": ["left right arrow with stroke", "direction, mapping, implication or flow"],
    "↯": ["downwards zigzag arrow", "direction, mapping, implication or flow"],
    "↰": ["upwards arrow with tip leftwards", "direction, mapping, implication or flow"],
    "↱": ["upwards arrow with tip rightwards", "direction, mapping, implication or flow"],
    "↲": ["downwards arrow with tip leftwards", "direction, mapping, implication or flow"],
    "↳": ["downwards arrow with tip rightwards", "direction, mapping, implication or flow"],
    "↴": ["rightwards arrow with corner downwards", "direction, mapping, implication or flow"],
    "↵": ["downwards arrow with corner leftwards", "direction, mapping, implication or flow"],
    "↶": ["anticlockwise top semicircle arrow", "direction, mapping, implication or flow"],
    "↷": ["clockwise top semicircle arrow", "direction, mapping, implication or flow"],
    "↺": ["anticlockwise open circle arrow", "direction, mapping, implication or flow"],
    "↻": ["clockwise open circle arrow", "direction, mapping, implication or flow"],
    "↼": ["leftwards harpoon with barb upwards", "direction, mapping, implication or flow"],
    "↽": ["leftwards harpoon with barb downwards", "direction, mapping, implication or flow"],
    "↾": ["upwards harpoon with barb rightwards", "direction, mapping, implication or flow"],
    "↿": ["upwards harpoon with barb leftwards", "direction, mapping, implication or flow"],
    "⇀": ["rightwards harpoon with barb upwards", "direction, mapping, implication or flow"],
    "⇁": ["rightwards harpoon with barb downwards", "direction, mapping, implication or flow"],
    "⇂": ["downwards harpoon with barb rightwards", "direction, mapping, implication or flow"],
    "⇃": ["downwards harpoon with barb leftwards", "direction, mapping, implication or flow"],
    "⇄": ["rightwards arrow over leftwards arrow", "direction, mapping, implication or flow"],
    "⇅": ["upwards arrow leftwards of downwards arrow", "direction, mapping, implication or flow"],
    "⇆": ["leftwards arrow over rightwards arrow", "direction, mapping, implication or flow"],
    "⇇": ["leftwards paired arrows", "direction, mapping, implication or flow"],
    "⇈": ["upwards paired arrows", "direction, mapping, implication or flow"],
    "⇉": ["rightwards paired arrows", "direction, mapping, implication or flow"],
    "⇊": ["downwards paired arrows", "direction, mapping, implication or flow"],
    "⇋": ["leftwards harpoon over rightwards harpoon", "direction, mapping, implication or flow"],
    "⇌": ["rightwards harpoon over leftwards harpoon", "direction, mapping, implication or flow"],
    "⇍": ["leftwards double arrow with stroke", "direction, mapping, implication or flow"],
    "⇎": ["left right double arrow with stroke", "direction, mapping, implication or flow"],
    "⇏": ["rightwards double arrow with stroke", "direction, mapping, implication or flow"],
    "⇐": ["leftwards double arrow", "direction, mapping, implication or flow"],
    "⇑": ["upwards double arrow", "direction, mapping, implication or flow"],
    "⇓": ["downwards double arrow", "direction, mapping, implication or flow"],
    "⇕": ["up down double arrow", "direction, mapping, implication or flow"],
    "⇖": ["north west double arrow", "direction, mapping, implication or flow"],
    "⇗": ["north east double arrow", "direction, mapping, implication or flow"],
    "⇘": ["south east double arrow", "direction, mapping, implication or flow"],
    "⇙": ["south west double arrow", "direction, mapping, implication or flow"],
    "⇚": ["leftwards triple arrow", "direction, mapping, implication or flow"],
    "⇛": ["rightwards triple arrow", "direction, mapping, implication or flow"],
    "⟵": ["long leftwards arrow", "direction, mapping, implication or flow"],
    "⟶": ["long rightwards arrow", "direction, mapping, implication or flow"],
    "⟷": ["long left right arrow", "direction, mapping, implication or flow"],
    "⟸": ["long leftwards double arrow", "direction, mapping, implication or flow"],
    "⟹": ["long rightwards double arrow", "direction, mapping, implication or flow"],
    "⟺": ["long left right double arrow", "direction, mapping, implication or flow"],
    "⟼": ["long rightwards arrow from bar", "direction, mapping, implication or flow"],
    "⤴": ["arrow pointing rightwards then curving upwards", "direction, mapping, implication or flow"],
    "⤵": ["arrow pointing rightwards then curving downwards", "direction, mapping, implication or flow"],
    "─": ["box drawings light horizontal", "draws frames, lines and strokes in text diagrams"],
    "━": ["box drawings heavy horizontal", "draws frames, lines and strokes in text diagrams"],
    "│": ["box drawings light vertical", "draws frames, lines and strokes in text diagrams"],
    "┃": ["box drawings heavy vertical", "draws frames, lines and strokes in text diagrams"],
    "┄": ["box drawings light triple dash horizontal", "draws frames, lines and strokes in text diagrams"],
    "┅": ["box drawings heavy triple dash horizontal", "draws frames, lines and strokes in text diagrams"],
    "┆": ["box drawings light triple dash vertical", "draws frames, lines and strokes in text diagrams"],
    "┇": ["box drawings heavy triple dash vertical", "draws frames, lines and strokes in text diagrams"],
    "┈": ["box drawings light quadruple dash horizontal", "draws frames, lines and strokes in text diagrams"],
    "┉": ["box drawings heavy quadruple dash horizontal", "draws frames, lines and strokes in text diagrams"],
    "┊": ["box drawings light quadruple dash vertical", "draws frames, lines and strokes in text diagrams"],
    "┋": ["box drawings heavy quadruple dash vertical", "draws frames, lines and strokes in text diagrams"],
    "┌": ["box drawings light down and right", "draws frames, lines and strokes in text diagrams"],
    "┐": ["box drawings light down and left", "draws frames, lines and strokes in text diagrams"],
    "└": ["box drawings light up and right", "draws frames, lines and strokes in text diagrams"],
    "┘": ["box drawings light up and left", "draws frames, lines and strokes in text diagrams"],
    "├": ["box drawings light vertical and right", "draws frames, lines and strokes in text diagrams"],
    "┤": ["box drawings light vertical and left", "draws frames, lines and strokes in text diagrams"],
    "┬": ["box drawings light down and horizontal", "draws frames, lines and strokes in text diagrams"],
    "┴": ["box drawings light up and horizontal", "draws frames, lines and strokes in text diagrams"],
    "┼": ["box drawings light vertical and horizontal", "draws frames, lines and strokes in text diagrams"],
    "═": ["box drawings double horizontal", "draws frames, lines and strokes in text diagrams"],
    "║": ["box drawings double vertical", "draws frames, lines and strokes in text diagrams"],
    "╒": ["box drawings down single and right double", "draws frames, lines and strokes in text diagrams"],
    "╓": ["box drawings down double and right single", "draws frames, lines and strokes in text diagrams"],
    "╔": ["box drawings double down and right", "draws frames, lines and strokes in text diagrams"],
    "╕": ["box drawings down single and left double", "draws frames, lines and strokes in text diagrams"],
    "╖": ["box drawings down double and left single", "draws frames, lines and strokes in text diagrams"],
    "╗": ["box drawings double down and left", "draws frames, lines and strokes in text diagrams"],
    "╘": ["box drawings up single and right double", "draws frames, lines and strokes in text diagrams"],
    "╙": ["box drawings up double and right single", "draws frames, lines and strokes in text diagrams"],
    "╚": ["box drawings double up and right", "draws frames, lines and strokes in text diagrams"],
    "╛": ["box drawings up single and left double", "draws frames, lines and strokes in text diagrams"],
    "╜": ["box drawings up double and left single", "draws frames, lines and strokes in text diagrams"],
    "╝": ["box drawings double up and left", "draws frames, lines and strokes in text diagrams"],
    "╞": ["box drawings vertical single and right double", "draws frames, lines and strokes in text diagrams"],
    "╟": ["box drawings vertical double and right single", "draws frames, lines and strokes in text diagrams"],
    "╠": ["box drawings double vertical and right", "draws frames, lines and strokes in text diagrams"],
    "╡": ["box drawings vertical single and left double", "draws frames, lines and strokes in text diagrams"],
    "╢": ["box drawings vertical double and left single", "draws frames, lines and strokes in text diagrams"],
    "╣": ["box drawings double vertical and left", "draws frames, lines and strokes in text diagrams"],
    "╤": ["box drawings down single and horizontal double", "draws frames, lines and strokes in text diagrams"],
    "╥": ["box drawings down double and horizontal single", "draws frames, lines and strokes in text diagrams"],
    "╦": ["box drawings double down and horizontal", "draws frames, lines and strokes in text diagrams"],
    "╧": ["box drawings up single and horizontal double", "draws frames, lines and strokes in text diagrams"],
    "╨": ["box drawings up double and horizontal single", "draws frames, lines and strokes in text diagrams"],
    "╩": ["box drawings double up and horizontal", "draws frames, lines and strokes in text diagrams"],
    "╪": ["box drawings vertical single and horizontal double", "draws frames, lines and strokes in text diagrams"],
    "╫": ["box drawings vertical double and horizontal single", "draws frames, lines and strokes in text diagrams"],
    "╬": ["box drawings double vertical and horizontal", "draws frames, lines and strokes in text diagrams"],
    "╭": ["box drawings light arc down and right", "draws frames, lines and strokes in text diagrams"],
    "╮": ["box drawings light arc down and left", "draws frames, lines and strokes in text diagrams"],
    "╯": ["box drawings light arc up and left", "draws frames, lines and strokes in text diagrams"],
    "╰": ["box drawings light arc up and right", "draws frames, lines and strokes in text diagrams"],
    "╱": ["box drawings light diagonal upper right to lower left", "draws frames, lines and strokes in text diagrams"],
    "╲": ["box drawings light diagonal upper left to lower right", "draws frames, lines and strokes in text diagrams"],
    "╳": ["box drawings light diagonal cross", "draws frames, lines and strokes in text diagrams"],
    "╴": ["box drawings light left", "draws frames, lines and strokes in text diagrams"],
    "╵": ["box drawings light up", "draws frames, lines and strokes in text diagrams"],
    "╶": ["box drawings light right", "draws frames, lines and strokes in text diagrams"],
    "╷": ["box drawings light down", "draws frames, lines and strokes in text diagrams"],
    "▀": ["upper half block", "draws frames, lines and strokes in text diagrams"],
    "▁": ["lower one eighth block", "draws frames, lines and strokes in text diagrams"],
    "▂": ["lower one quarter block", "draws frames, lines and strokes in text diagrams"],
    "▃": ["lower three eighths block", "draws frames, lines and strokes in text diagrams"],
    "▄": ["lower half block", "draws frames, lines and strokes in text diagrams"],
    "▅": ["lower five eighths block", "draws frames, lines and strokes in text diagrams"],
    "▆": ["lower three quarters block", "draws frames, lines and strokes in text diagrams"],
    "▇": ["lower seven eighths block", "draws frames, lines and strokes in text diagrams"],
    "█": ["full block", "draws frames, lines and strokes in text diagrams"],
    "▉": ["left seven eighths block", "draws frames, lines and strokes in text diagrams"],
    "▊": ["left three quarters block", "draws frames, lines and strokes in text diagrams"],
    "▋": ["left five eighths block", "draws frames, lines and strokes in text diagrams"],
    "▌": ["left half block", "draws frames, lines and strokes in text diagrams"],
    "▍": ["left three eighths block", "draws frames, lines and strokes in text diagrams"],
    "▎": ["left one quarter block", "draws frames, lines and strokes in text diagrams"],
    "▏": ["left one eighth block", "draws frames, lines and strokes in text diagrams"],
    "▐": ["right half block", "draws frames, lines and strokes in text diagrams"],
    "░": ["light shade", "draws frames, lines and strokes in text diagrams"],
    "▒": ["medium shade", "draws frames, lines and strokes in text diagrams"],
    "▓": ["dark shade", "draws frames, lines and strokes in text diagrams"],
    "▔": ["upper one eighth block", "draws frames, lines and strokes in text diagrams"],
    "▕": ["right one eighth block", "draws frames, lines and strokes in text diagrams"],
    "■": ["black square", "draws frames, lines and strokes in text diagrams"],
    "▪": ["black small square", "draws frames, lines and strokes in text diagrams"],
    "▫": ["white small square", "draws frames, lines and strokes in text diagrams"],
    "▬": ["black rectangle", "draws frames, lines and strokes in text diagrams"],
    "▭": ["white rectangle", "draws frames, lines and strokes in text diagrams"],
    "▮": ["black vertical rectangle", "draws frames, lines and strokes in text diagrams"],
    "▯": ["white vertical rectangle", "draws frames, lines and strokes in text diagrams"],
    "▲": ["black up-pointing triangle", "draws frames, lines and strokes in text diagrams"],
    "▶": ["black right-pointing triangle", "draws frames, lines and strokes in text diagrams"],
    "▷": ["white right-pointing triangle", "draws frames, lines and strokes in text diagrams"],
    "▼": ["black down-pointing triangle", "draws frames, lines and strokes in text diagrams"],
    "◀": ["black left-pointing triangle", "draws frames, lines and strokes in text diagrams"],
    "◁": ["white left-pointing triangle", "draws frames, lines and strokes in text diagrams"],
    "◆": ["black diamond", "draws frames, lines and strokes in text diagrams"],
    "◇": ["white diamond", "draws frames, lines and strokes in text diagrams"],
    "◎": ["bullseye", "draws frames, lines and strokes in text diagrams"],
    "●": ["black circle", "draws frames, lines and strokes in text diagrams"],
    "◐": ["circle with left half black", "draws frames, lines and strokes in text diagrams"],
    "◑": ["circle with right half black", "draws frames, lines and strokes in text diagrams"],
    "◒": ["circle with lower half black", "draws frames, lines and strokes in text diagrams"],
    "◓": ["circle with upper half black", "draws frames, lines and strokes in text diagrams"],
    "◯": ["large circle", "draws frames, lines and strokes in text diagrams"],
    "א": ["Hebrew letter alef", "≈ unity, potential, origin, silence, breath, beginning, wholeness, possibility, ground, the unspoken, oneness, source", "value 1"],
    "ב": ["Hebrew letter bet", "≈ house, container, vessel, interior, dwelling, structure, holding, enclosure, home, frame, place, inside", "value 2"],
    "ג": ["Hebrew letter gimel", "≈ movement, carrying, transfer, flow, channel, bridge, giving, benefit, transport, exchange, reward, journey", "value 3"],
    "ד": ["Hebrew letter dalet", "≈ door, threshold, entry, passage, opening, access, gateway, input, path, approach, admission, crossing", "value 4"],
    "ה": ["Hebrew letter he", "≈ window, revelation, breath, expression, presence, display, showing, attention, emphasis, view, aspect, being", "value 5"],
    "ו": ["Hebrew letter vav", "≈ hook, connection, and, joining, link, pillar, continuity, addition, binding, sequence, attachment, conjunction", "value 6"],
    "ז": ["Hebrew letter zayin", "≈ time, sword, sustenance, cutting, distinction, nourishment, moment, decision, division, memory, rhythm, edge", "value 7"],
    "ח": ["Hebrew letter het", "≈ fence, boundary, life, protection, enclosure, limit, grace, safety, perimeter, separation, privacy, wall", "value 8"],
    "ט": ["Hebrew letter tet", "≈ hidden, coil, concealment, latency, goodness, interior, embedding, implication, wrapping, reserve, the within, potential", "value 9"],
    "י": ["Hebrew letter yod", "≈ hand, point, seed, smallest, unit, spark, action, minimum, atom, potency, initiation, instance", "value 10"],
    "כ": ["Hebrew letter kaf", "≈ palm, capacity, ability, agency, holding, crown, power, readiness, grasp, means, control, capability", "value 20"],
    "ל": ["Hebrew letter lamed", "≈ teaching, learning, aspiration, goad, ascent, drive, guidance, direction, study, instruction, purpose, striving", "value 30"],
    "מ": ["Hebrew letter mem", "≈ water, source, flow, wisdom, womb, origin, depth, fluidity, collective, mass, nourishment, memory", "value 40"],
    "נ": ["Hebrew letter nun", "≈ fish, soul, emergence, faithfulness, continuity, life, individual, offspring, persistence, growth, propagation, purpose", "value 50"],
    "ס": ["Hebrew letter samekh", "≈ support, foundation, circle, cycle, prop, base, framework, stability, sustenance, order, repetition, catalogue", "value 60"],
    "ע": ["Hebrew letter ayin", "≈ eye, perception, seeing, insight, spring, depth, attention, observation, awareness, sense, witness, notice", "value 70"],
    "פ": ["Hebrew letter pe", "≈ mouth, speech, expression, command, voice, output, utterance, language, statement, communication, declaration, opening", "value 80"],
    "צ": ["Hebrew letter tsadi", "≈ righteousness, correctness, discipline, pursuit, justice, alignment, precision, aim, validation, integrity, rigor, judgment", "value 90"],
    "ק": ["Hebrew letter qof", "≈ return, cycle, loop, recurrence, back of the head, sanctity, repetition, echo, reflection, imitation, aftermath, holiness", "value 100"],
    "ר": ["Hebrew letter resh", "≈ head, beginning, identity, leader, governor, first, self, chief, principle, origin, mind, invariant", "value 200"],
    "ש": ["Hebrew letter shin", "≈ fire, transformation, tooth, change, consumption, energy, purification, refinement, intensity, process, conversion, power", "value 300"],
    "ת": ["Hebrew letter tav", "≈ mark, sign, truth, completion, seal, end, covenant, signature, finish, confirmation, result, closure", "value 400"],
    "ך": ["Hebrew letter final kaf", "≈ palm at rest, fulfilled capacity, closed hand, completed agency, held, kept, reserve, done", "value 20 (final form: 500 in the extended count)"],
    "ם": ["Hebrew letter final mem", "≈ sealed source, enclosure, completeness, registry, archive, storage, collection, record, repository, containment", "value 40 (final form: 600 in the extended count)"],
    "ן": ["Hebrew letter final nun", "≈ extended soul, terminal point, fulfilled purpose, persistence to the end, reach, lineage, extension, conclusion", "value 50 (final form: 700 in the extended count)"],
    "ף": ["Hebrew letter final pe", "≈ final word, complete expression, closing statement, conclusion, last utterance, summary, verdict, final say", "value 80 (final form: 800 in the extended count)"],
    "ץ": ["Hebrew letter final tsadi", "≈ furthest correctness, ultimate pursuit, limit of rigor, final alignment, extended discipline, fulfilled justice", "value 90 (final form: 900 in the extended count)"],
    "ים": ["plural ending (masculine); the word for sea"],
    "יה": ["the divine name Yah"],
    "אמש": ["the three mothers: air, water, fire"],
    "α": ["greek small letter alpha", "angle; coefficient; significance level"],
    "β": ["greek small letter beta", "angle; coefficient; beta function"],
    "γ": ["greek small letter gamma", "angle; Euler–Mascheroni constant; Lorentz factor"],
    "δ": ["greek small letter delta", "small change; Dirac delta; Kronecker delta"],
    "ζ": ["greek small letter zeta", "Riemann zeta function; damping ratio"],
    "η": ["greek small letter eta", "efficiency; viscosity"],
    "θ": ["greek small letter theta", "angle; temperature; parameter"],
    "ι": ["greek small letter iota", "used as a variable or constant"],
    "κ": ["greek small letter kappa", "curvature; conductivity"],
    "λ": ["greek small letter lamda", "wavelength; eigenvalue; lambda (anonymous function)"],
    "μ": ["greek small letter mu", "mean; micro- (10⁻⁶); friction coefficient"],
    "ν": ["greek small letter nu", "frequency"],
    "ξ": ["greek small letter xi", "random variable; coordinate"],
    "ο": ["greek small letter omicron", "used as a variable or constant"],
    "ρ": ["greek small letter rho", "density; correlation"],
    "σ": ["greek small letter sigma", "standard deviation; stress; sum (as Σ)"],
    "τ": ["greek small letter tau", "time constant; torque; 2π"],
    "υ": ["greek small letter upsilon", "used as a variable or constant"],
    "φ": ["greek small letter phi", "golden ratio; angle; potential"],
    "χ": ["greek small letter chi", "chi-squared; characteristic"],
    "ψ": ["greek small letter psi", "wavefunction"],
    "ω": ["greek small letter omega", "angular frequency"],
    "Γ": ["greek capital letter gamma", "gamma function"],
    "Θ": ["greek capital letter theta", "asymptotic bound (Θ(n))"],
    "Λ": ["greek capital letter lamda", "cosmological constant"],
    "Ξ": ["greek capital letter xi", "grand canonical partition"],
    "Π": ["greek capital letter pi", "product"],
    "Φ": ["greek capital letter phi", "flux; golden ratio"],
    "Ψ": ["greek capital letter psi", "wavefunction"],
    "1": ["digit one", "digit"],
    "2": ["digit two", "digit"],
    "3": ["digit three", "digit"],
    "4": ["digit four", "digit"],
    "5": ["digit five", "digit"],
    "6": ["digit six", "digit"],
    "7": ["digit seven", "digit"],
    "8": ["digit eight", "digit"],
    "9": ["digit nine", "digit"],
    "⁰": ["superscript zero", "exponent or power"],
    "¹": ["superscript one", "exponent or power"],
    "²": ["superscript two", "exponent or power"],
    "³": ["superscript three", "exponent or power"],
    "⁴": ["superscript four", "exponent or power"],
    "⁵": ["superscript five", "exponent or power"],
    "⁶": ["superscript six", "exponent or power"],
    "⁷": ["superscript seven", "exponent or power"],
    "⁸": ["superscript eight", "exponent or power"],
    "⁹": ["superscript nine", "exponent or power"],
    "₀": ["subscript zero", "index or label"],
    "₁": ["subscript one", "index or label"],
    "₂": ["subscript two", "index or label"],
    "₃": ["subscript three", "index or label"],
    "₄": ["subscript four", "index or label"],
    "₅": ["subscript five", "index or label"],
    "₆": ["subscript six", "index or label"],
    "₇": ["subscript seven", "index or label"],
    "₈": ["subscript eight", "index or label"],
    "₉": ["subscript nine", "index or label"],
    "½": ["vulgar fraction one half", "fraction"],
    "⅓": ["vulgar fraction one third", "fraction"],
    "⅔": ["vulgar fraction two thirds", "fraction"],
    "¼": ["vulgar fraction one quarter", "fraction"],
    "¾": ["vulgar fraction three quarters", "fraction"],
    "⅛": ["vulgar fraction one eighth", "fraction"],
    "ⅰ": ["small roman numeral one", "roman numeral"],
    "ⅱ": ["small roman numeral two", "roman numeral"],
    "ⅲ": ["small roman numeral three", "roman numeral"],
    "ⅳ": ["small roman numeral four", "roman numeral"],
    "ⅴ": ["small roman numeral five", "roman numeral"],
    "ⅵ": ["small roman numeral six", "roman numeral"],
    "ⅶ": ["small roman numeral seven", "roman numeral"],
    "ⅷ": ["small roman numeral eight", "roman numeral"],
    "ⅸ": ["small roman numeral nine", "roman numeral"],
    "ⅹ": ["small roman numeral ten", "roman numeral"],
    "\"": ["quotation mark"],
    "`": ["grave accent"],
    "¥": ["yen sign"],
    "†": ["dagger"],
    "‡": ["double dagger"],
    "•": ["bullet"],
    "‣": ["triangular bullet"],
    "◦": ["white bullet"],
    "‱": ["per ten thousand sign"],
    "№": ["numero sign"],
    "℗": ["sound recording copyright"],
    "©": ["copyright sign"],
    "®": ["registered sign"],
    "™": ["trade mark sign"],
}

EXAMPLES = {
    "|": ["|−3| = 3", "3 | 12  (3 divides 12)", "P(A | B)"],
    "/": ["6 / 2 = 3", "60 km/h", "and/or"],
    "\\": ["{1,2,3} \\ {2} = {1,3}"],
    "_": ["x_1", "__slot__"],
    "-": ["7 − 2 = 5", "pages 1-5"],
    "+": ["2 + 3 = 5", "A + B"],
    "=": ["x = 4", "2 + 2 = 4"],
    "≠": ["3 ≠ 4"],
    "<": ["2 < 5", "verb < word"],
    ">": ["9 > 4"],
    "≤": ["x ≤ 10"],
    "≥": ["n ≥ 0"],
    "^": ["2^3 = 8"],
    "[": ["[0, 1]", "a[i]"],
    "]": ["[a, b]"],
    "#": ["#items = 4", "# a comment"],
    "*": ["3 * 4 = 12", "f * g"],
    "×": ["3 × 4 = 12", "a × b", "3×4 grid"],
    "±": ["5 ± 0.1"],
    "⊥": ["a ⊥ b"],
    "∥": ["a ∥ b"],
    "∠": ["∠ABC = 90°"],
    "△": ["△ABC", "A △ B"],
    "□": ["□p  (necessarily p)"],
    "∧": ["p ∧ q"],
    "∨": ["p ∨ q"],
    "¬": ["¬p"],
    "→": ["A → B", "f: A → B", "x → 0"],
    "⇒": ["p ⇒ q"],
    "⇔": ["p ⇔ q"],
    "↑": ["prices ↑"],
    "Σ": ["Σ xᵢ", "Σ₁¹⁰ n = 55"],
    "Δ": ["Δx = x₂ − x₁"],
    "∇": ["∇f"],
    "√": ["√9 = 3", "√2 ≈ 1.414"],
    "∀": ["∀x (x = x)"],
    "⊤": ["Aᵀ", "⊤ ∧ p = p"],
    "⊢": ["Γ ⊢ φ"],
    "0": ["0 + a = a", "(0, 0)"],
    "§": ["§ 3.2", "§Echo§"],
    "°": ["90°", "25 °C"],
    "∞": ["n → ∞"],
    ":": ["3:4", "{x : x > 0}", "a:b::c:d"],
    "(": ["(2 + 3) × 4", "f(x)"],
    ")": ["(a, b)"],
    "{": ["{1, 2, 3}"],
    "}": ["{a, b}"],
    ".": ["3.14", "obj.name"],
    ",": ["(x, y)", "1,000"],
    "'": ["f′(x)", "5′ 10″"],
    "~": ["≈ but looser: x ~ 3", "X ~ N(0,1)"],
    "∘": ["(f ∘ g)(x) = f(g(x))"],
    "○": ["○ empty marker"],
    "∫": ["∫ x dx = x²/2 + C"],
    "∮": ["∮ E·dA"],
    "∂": ["∂f/∂x", "∂A"],
    "⊂": ["{1} ⊂ {1,2}"],
    "⊃": ["{1,2} ⊃ {1}"],
    "∪": ["{1} ∪ {2} = {1,2}"],
    "∩": ["{1,2} ∩ {2,3} = {2}"],
    "≈": ["π ≈ 3.14", "ר ≈ head, beginning, identity"],
    "∼": ["f ∼ g"],
    "∴": ["∴ x = 2"],
    "∵": ["∵ x > 0"],
    "ε": ["ε > 0"],
    "%": ["50% of 8 = 4", "7 % 3 = 1", "% → step into the underside"],
    "$": ["$5", "$x$"],
    ";": ["a; b; c"],
    "…": ["1, 2, …, n"],
    "&": ["A & B"],
    "@": ["A @ B", "@decorator"],
    "?": ["x = ?", "c ? a : b"],
    "!": ["5! = 120", "∃! x"],
    "÷": ["12 ÷ 4 = 3"],
    "‰": ["5‰ = 0.5%"],
    "₪": ["₪20"],
    "π": ["C = 2πr", "π ≈ 3.14159"],
    "∈": ["2 ∈ ℕ"],
    "∉": ["−1 ∉ ℕ"],
    "∅": ["A ∩ B = ∅"],
    "∝": ["F ∝ 1/r²"],
    "⊕": ["1 ⊕ 1 = 0"],
    "⊗": ["V ⊗ W"],
    "¶": ["¶ 2"],
    "¢": ["50¢"],
    "€": ["€10"],
    "£": ["£10"],
    "ℵ": ["ℵ₀"],
    "ℏ": ["E = ℏω"],
    "Ω": ["10 Ω"],
    "-%": ["-% → lift back up"],
    ":-": ["Verb = a Word :- Denote - an Action"],
    "=T": ["◇ x > 0 =T"],
    "=F": ["◇ x < 0 =F"],
    "::": ["(a<b):(c<d)::(e<f):(g<h)", "day:night::light:dark"],
    "__י__": ["__י__/ opens a sequence"],
    "|x|": ["|{(a<b):(c<d)::(?):(?)}|"],
    "||": ["||__||"],
    "__": ["__word__"],
    "§ר§": ["§ר§ present on both faces"],
    "⟨": ["⟨x⟩"],
    "⟩": ["⟨x⟩"],
    "⟦": ["⟦x⟧"],
    "⟧": ["⟦x⟧"],
    "⟪": ["⟪x⟫"],
    "⟫": ["⟪x⟫"],
    "⌈": ["⌈x⌉"],
    "⌉": ["⌈x⌉"],
    "⌊": ["⌊x⌋"],
    "⌋": ["⌊x⌋"],
    "⦃": ["⦃x⦄"],
    "⦄": ["⦃x⦄"],
    "⦅": ["⦅x⦆"],
    "⦆": ["⦅x⦆"],
    "⦇": ["⦇x⦈"],
    "⦈": ["⦇x⦈"],
    "⦉": ["⦉x⦊"],
    "⦊": ["⦉x⦊"],
    "⦋": ["⦋x⦌"],
    "⦌": ["⦋x⦌"],
    "⦍": ["⦍x⦎"],
    "⦎": ["⦍x⦎"],
    "⦏": ["⦏x⦐"],
    "⦐": ["⦏x⦐"],
    "⦑": ["⦑x⦒"],
    "⦒": ["⦑x⦒"],
    "⦓": ["⦓x⦔"],
    "⦔": ["⦓x⦔"],
    "⦕": ["⦕x⦖"],
    "⦖": ["⦕x⦖"],
    "⦗": ["⦗x⦘"],
    "⦘": ["⦗x⦘"],
    "⁅": ["⁅x⁆"],
    "⁆": ["⁅x⁆"],
    "〈": ["〈x〉"],
    "〉": ["〈x〉"],
    "《": ["《x》"],
    "》": ["《x》"],
    "「": ["「x」"],
    "」": ["「x」"],
    "『": ["『x』"],
    "』": ["『x』"],
    "【": ["【x】"],
    "】": ["【x】"],
    "〔": ["〔x〕"],
    "〕": ["〔x〕"],
    "〖": ["〖x〗"],
    "〗": ["〖x〗"],
    "〘": ["〘x〙"],
    "〙": ["〘x〙"],
    "〚": ["〚x〛"],
    "〛": ["〚x〛"],
    "‹": ["‹x›"],
    "›": ["‹x›"],
    "«": ["«x»"],
    "»": ["«x»"],
    "−": ["a − b"],
    "∓": ["a ∓ b"],
    "·": ["a · b"],
    "∙": ["a ∙ b"],
    "≃": ["a ≃ b"],
    "≅": ["a ≅ b"],
    "≡": ["a ≡ b"],
    "≢": ["a ≢ b"],
    "≪": ["a ≪ b"],
    "≫": ["a ≫ b"],
    "∛": ["a ∛ b"],
    "∜": ["a ∜ b"],
    "∑": ["a ∑ b"],
    "∏": ["a ∏ b"],
    "∐": ["a ∐ b"],
    "∬": ["a ∬ b"],
    "∭": ["a ∭ b"],
    "∆": ["a ∆ b"],
    "∋": ["a ∋ b"],
    "∌": ["a ∌ b"],
    "⊆": ["a ⊆ b"],
    "⊇": ["a ⊇ b"],
    "⊄": ["a ⊄ b"],
    "⊅": ["a ⊅ b"],
    "∖": ["a ∖ b"],
    "∃": ["a ∃ b"],
    "∄": ["a ∄ b"],
    "⊻": ["a ⊻ b"],
    "⊼": ["a ⊼ b"],
    "⊽": ["a ⊽ b"],
    "⊖": ["a ⊖ b"],
    "⊘": ["a ⊘ b"],
    "⊙": ["a ⊙ b"],
    "⊣": ["a ⊣ b"],
    "⊨": ["a ⊨ b"],
    "∶": ["a ∶ b"],
    "∷": ["a ∷ b"],
    "′": ["a ′ b"],
    "″": ["a ″ b"],
    "‴": ["a ‴ b"],
    "ℶ": ["a ℶ b"],
    "ℓ": ["a ℓ b"],
    "℘": ["a ℘ b"],
    "ℜ": ["a ℜ b"],
    "ℑ": ["a ℑ b"],
    "∡": ["a ∡ b"],
    "∢": ["a ∢ b"],
    "⊾": ["a ⊾ b"],
    "▽": ["a ▽ b"],
    "⟂": ["a ⟂ b"],
    "∦": ["a ∦ b"],
    "←": ["A ← B"],
    "↓": ["A ↓ B"],
    "↔": ["A ↔ B"],
    "↕": ["A ↕ B"],
    "↖": ["A ↖ B"],
    "↗": ["A ↗ B"],
    "↘": ["A ↘ B"],
    "↙": ["A ↙ B"],
    "↚": ["A ↚ B"],
    "↛": ["A ↛ B"],
    "↜": ["A ↜ B"],
    "↝": ["A ↝ B"],
    "↞": ["A ↞ B"],
    "↟": ["A ↟ B"],
    "↠": ["A ↠ B"],
    "↡": ["A ↡ B"],
    "↢": ["A ↢ B"],
    "↣": ["A ↣ B"],
    "↤": ["A ↤ B"],
    "↥": ["A ↥ B"],
    "↦": ["A ↦ B"],
    "↧": ["A ↧ B"],
    "↨": ["A ↨ B"],
    "↩": ["A ↩ B"],
    "↪": ["A ↪ B"],
    "↫": ["A ↫ B"],
    "↬": ["A ↬ B"],
    "↭": ["A ↭ B"],
    "↮": ["A ↮ B"],
    "↯": ["A ↯ B"],
    "↰": ["A ↰ B"],
    "↱": ["A ↱ B"],
    "↲": ["A ↲ B"],
    "↳": ["A ↳ B"],
    "↴": ["A ↴ B"],
    "↵": ["A ↵ B"],
    "↶": ["A ↶ B"],
    "↷": ["A ↷ B"],
    "↺": ["A ↺ B"],
    "↻": ["A ↻ B"],
    "↼": ["A ↼ B"],
    "↽": ["A ↽ B"],
    "↾": ["A ↾ B"],
    "↿": ["A ↿ B"],
    "⇀": ["A ⇀ B"],
    "⇁": ["A ⇁ B"],
    "⇂": ["A ⇂ B"],
    "⇃": ["A ⇃ B"],
    "⇄": ["A ⇄ B"],
    "⇅": ["A ⇅ B"],
    "⇆": ["A ⇆ B"],
    "⇇": ["A ⇇ B"],
    "⇈": ["A ⇈ B"],
    "⇉": ["A ⇉ B"],
    "⇊": ["A ⇊ B"],
    "⇋": ["A ⇋ B"],
    "⇌": ["A ⇌ B"],
    "⇍": ["A ⇍ B"],
    "⇎": ["A ⇎ B"],
    "⇏": ["A ⇏ B"],
    "⇐": ["A ⇐ B"],
    "⇑": ["A ⇑ B"],
    "⇓": ["A ⇓ B"],
    "⇕": ["A ⇕ B"],
    "⇖": ["A ⇖ B"],
    "⇗": ["A ⇗ B"],
    "⇘": ["A ⇘ B"],
    "⇙": ["A ⇙ B"],
    "⇚": ["A ⇚ B"],
    "⇛": ["A ⇛ B"],
    "⟵": ["A ⟵ B"],
    "⟶": ["A ⟶ B"],
    "⟷": ["A ⟷ B"],
    "⟸": ["A ⟸ B"],
    "⟹": ["A ⟹ B"],
    "⟺": ["A ⟺ B"],
    "⟼": ["A ⟼ B"],
    "⤴": ["A ⤴ B"],
    "⤵": ["A ⤵ B"],
    "─": ["─────", "┌─┐"],
    "━": ["━━━━━", "┌━┐"],
    "│": ["│││││", "┌│┐"],
    "┃": ["┃┃┃┃┃", "┌┃┐"],
    "┄": ["┄┄┄┄┄", "┌┄┐"],
    "┅": ["┅┅┅┅┅", "┌┅┐"],
    "┆": ["┆┆┆┆┆", "┌┆┐"],
    "┇": ["┇┇┇┇┇", "┌┇┐"],
    "┈": ["┈┈┈┈┈", "┌┈┐"],
    "┉": ["┉┉┉┉┉", "┌┉┐"],
    "┊": ["┊┊┊┊┊", "┌┊┐"],
    "┋": ["┋┋┋┋┋", "┌┋┐"],
    "┌": ["┌┌┌┌┌", "┌─┌"],
    "┐": ["┐┐┐┐┐", "┐─┐"],
    "└": ["└└└└└", "└─└"],
    "┘": ["┘┘┘┘┘", "┘─┘"],
    "├": ["├├├├├", "┌├┐"],
    "┤": ["┤┤┤┤┤", "┌┤┐"],
    "┬": ["┬┬┬┬┬", "┌┬┐"],
    "┴": ["┴┴┴┴┴", "┌┴┐"],
    "┼": ["┼┼┼┼┼", "┌┼┐"],
    "═": ["═════", "┌═┐"],
    "║": ["║║║║║", "┌║┐"],
    "╒": ["╒╒╒╒╒", "┌╒┐"],
    "╓": ["╓╓╓╓╓", "┌╓┐"],
    "╔": ["╔╔╔╔╔", "┌╔┐"],
    "╕": ["╕╕╕╕╕", "┌╕┐"],
    "╖": ["╖╖╖╖╖", "┌╖┐"],
    "╗": ["╗╗╗╗╗", "┌╗┐"],
    "╘": ["╘╘╘╘╘", "┌╘┐"],
    "╙": ["╙╙╙╙╙", "┌╙┐"],
    "╚": ["╚╚╚╚╚", "┌╚┐"],
    "╛": ["╛╛╛╛╛", "┌╛┐"],
    "╜": ["╜╜╜╜╜", "┌╜┐"],
    "╝": ["╝╝╝╝╝", "┌╝┐"],
    "╞": ["╞╞╞╞╞", "┌╞┐"],
    "╟": ["╟╟╟╟╟", "┌╟┐"],
    "╠": ["╠╠╠╠╠", "┌╠┐"],
    "╡": ["╡╡╡╡╡", "┌╡┐"],
    "╢": ["╢╢╢╢╢", "┌╢┐"],
    "╣": ["╣╣╣╣╣", "┌╣┐"],
    "╤": ["╤╤╤╤╤", "┌╤┐"],
    "╥": ["╥╥╥╥╥", "┌╥┐"],
    "╦": ["╦╦╦╦╦", "┌╦┐"],
    "╧": ["╧╧╧╧╧", "┌╧┐"],
    "╨": ["╨╨╨╨╨", "┌╨┐"],
    "╩": ["╩╩╩╩╩", "┌╩┐"],
    "╪": ["╪╪╪╪╪", "┌╪┐"],
    "╫": ["╫╫╫╫╫", "┌╫┐"],
    "╬": ["╬╬╬╬╬", "┌╬┐"],
    "╭": ["╭╭╭╭╭", "┌╭┐"],
    "╮": ["╮╮╮╮╮", "┌╮┐"],
    "╯": ["╯╯╯╯╯", "┌╯┐"],
    "╰": ["╰╰╰╰╰", "┌╰┐"],
    "╱": ["╱╱╱╱╱", "┌╱┐"],
    "╲": ["╲╲╲╲╲", "┌╲┐"],
    "╳": ["╳╳╳╳╳", "┌╳┐"],
    "╴": ["╴╴╴╴╴", "┌╴┐"],
    "╵": ["╵╵╵╵╵", "┌╵┐"],
    "╶": ["╶╶╶╶╶", "┌╶┐"],
    "╷": ["╷╷╷╷╷", "┌╷┐"],
    "▀": ["▀▀▀▀▀", "┌▀┐"],
    "▁": ["▁▁▁▁▁", "┌▁┐"],
    "▂": ["▂▂▂▂▂", "┌▂┐"],
    "▃": ["▃▃▃▃▃", "┌▃┐"],
    "▄": ["▄▄▄▄▄", "┌▄┐"],
    "▅": ["▅▅▅▅▅", "┌▅┐"],
    "▆": ["▆▆▆▆▆", "┌▆┐"],
    "▇": ["▇▇▇▇▇", "┌▇┐"],
    "█": ["█████", "┌█┐"],
    "▉": ["▉▉▉▉▉", "┌▉┐"],
    "▊": ["▊▊▊▊▊", "┌▊┐"],
    "▋": ["▋▋▋▋▋", "┌▋┐"],
    "▌": ["▌▌▌▌▌", "┌▌┐"],
    "▍": ["▍▍▍▍▍", "┌▍┐"],
    "▎": ["▎▎▎▎▎", "┌▎┐"],
    "▏": ["▏▏▏▏▏", "┌▏┐"],
    "▐": ["▐▐▐▐▐", "┌▐┐"],
    "░": ["░░░░░", "┌░┐"],
    "▒": ["▒▒▒▒▒", "┌▒┐"],
    "▓": ["▓▓▓▓▓", "┌▓┐"],
    "▔": ["▔▔▔▔▔", "┌▔┐"],
    "▕": ["▕▕▕▕▕", "┌▕┐"],
    "■": ["■■■■■", "┌■┐"],
    "▪": ["▪▪▪▪▪", "┌▪┐"],
    "▫": ["▫▫▫▫▫", "┌▫┐"],
    "▬": ["▬▬▬▬▬", "┌▬┐"],
    "▭": ["▭▭▭▭▭", "┌▭┐"],
    "▮": ["▮▮▮▮▮", "┌▮┐"],
    "▯": ["▯▯▯▯▯", "┌▯┐"],
    "▲": ["▲▲▲▲▲", "┌▲┐"],
    "▶": ["▶▶▶▶▶", "┌▶┐"],
    "▷": ["▷▷▷▷▷", "┌▷┐"],
    "▼": ["▼▼▼▼▼", "┌▼┐"],
    "◀": ["◀◀◀◀◀", "┌◀┐"],
    "◁": ["◁◁◁◁◁", "┌◁┐"],
    "◆": ["◆◆◆◆◆", "┌◆┐"],
    "◇": ["◇◇◇◇◇", "┌◇┐"],
    "◎": ["◎◎◎◎◎", "┌◎┐"],
    "●": ["●●●●●", "┌●┐"],
    "◐": ["◐◐◐◐◐", "┌◐┐"],
    "◑": ["◑◑◑◑◑", "┌◑┐"],
    "◒": ["◒◒◒◒◒", "┌◒┐"],
    "◓": ["◓◓◓◓◓", "┌◓┐"],
    "◯": ["◯◯◯◯◯", "┌◯┐"],
    "א": ["אור (light)"],
    "ב": ["בית (house)"],
    "ג": ["גמל (camel)"],
    "ד": ["דלת (door)"],
    "ה": ["הר (mountain)"],
    "ו": ["ורד (rose)"],
    "ז": ["זמן (time)"],
    "ח": ["חיים (life)"],
    "ט": ["טוב (good)"],
    "י": ["יד (hand)"],
    "כ": ["כף (palm)"],
    "ל": ["לב (heart)"],
    "מ": ["מים (water)"],
    "נ": ["נר (candle)"],
    "ס": ["ספר (book)"],
    "ע": ["עין (eye)"],
    "פ": ["פה (mouth)"],
    "צ": ["צדק (justice)"],
    "ק": ["קול (voice)"],
    "ר": ["ראש (head)"],
    "ש": ["שמש (sun)"],
    "ת": ["תורה (teaching)"],
    "ך": ["מלך (king), final form"],
    "ם": ["שלום (peace), final form"],
    "ן": ["בן (son), final form"],
    "ף": ["כסף (silver), final form"],
    "ץ": ["ארץ (land), final form"],
    "ים": ["שמים (heavens)"],
    "יה": ["הללויה (halleluyah)"],
    "אמש": ["א מ ש: the three mothers"],
    "α": ["α + β + γ = 180°", "α₁, α₂"],
    "β": ["let β = 2", "β₁, β₂"],
    "γ": ["let γ = 2", "γ₁, γ₂"],
    "δ": ["δ → 0", "δ₁, δ₂"],
    "ζ": ["let ζ = 2", "ζ₁, ζ₂"],
    "η": ["let η = 2", "η₁, η₂"],
    "θ": ["sin θ", "θ₁, θ₂"],
    "ι": ["let ι = 2", "ι₁, ι₂"],
    "κ": ["let κ = 2", "κ₁, κ₂"],
    "λ": ["c = fλ", "λ₁, λ₂"],
    "μ": ["μ = 0, σ = 1", "μ₁, μ₂"],
    "ν": ["let ν = 2", "ν₁, ν₂"],
    "ξ": ["let ξ = 2", "ξ₁, ξ₂"],
    "ο": ["let ο = 2", "ο₁, ο₂"],
    "ρ": ["let ρ = 2", "ρ₁, ρ₂"],
    "σ": ["μ ± σ", "σ₁, σ₂"],
    "τ": ["let τ = 2", "τ₁, τ₂"],
    "υ": ["let υ = 2", "υ₁, υ₂"],
    "φ": ["let φ = 2", "φ₁, φ₂"],
    "χ": ["let χ = 2", "χ₁, χ₂"],
    "ψ": ["let ψ = 2", "ψ₁, ψ₂"],
    "ω": ["ω = 2πf", "ω₁, ω₂"],
    "Γ": ["let Γ = 2", "Γ₁, Γ₂"],
    "Θ": ["let Θ = 2", "Θ₁, Θ₂"],
    "Λ": ["let Λ = 2", "Λ₁, Λ₂"],
    "Ξ": ["let Ξ = 2", "Ξ₁, Ξ₂"],
    "Π": ["Π n", "Π₁, Π₂"],
    "Φ": ["Φ = BA", "Φ₁, Φ₂"],
    "Ψ": ["Ψ(x, t)", "Ψ₁, Ψ₂"],
    "1": ["110"],
    "2": ["220"],
    "3": ["330"],
    "4": ["440"],
    "5": ["550"],
    "6": ["660"],
    "7": ["770"],
    "8": ["880"],
    "9": ["990"],
    "⁰": ["x⁰"],
    "¹": ["x¹"],
    "²": ["x²"],
    "³": ["x³"],
    "⁴": ["x⁴"],
    "⁵": ["x⁵"],
    "⁶": ["x⁶"],
    "⁷": ["x⁷"],
    "⁸": ["x⁸"],
    "⁹": ["x⁹"],
    "₀": ["x₀"],
    "₁": ["x₁"],
    "₂": ["x₂"],
    "₃": ["x₃"],
    "₄": ["x₄"],
    "₅": ["x₅"],
    "₆": ["x₆"],
    "₇": ["x₇"],
    "₈": ["x₈"],
    "₉": ["x₉"],
    "½": ["½ + ½"],
    "⅓": ["⅓ + ⅓"],
    "⅔": ["⅔ + ⅔"],
    "¼": ["¼ + ¼"],
    "¾": ["¾ + ¾"],
    "⅛": ["⅛ + ⅛"],
    "ⅰ": ["ⅰ (roman numeral)"],
    "ⅱ": ["ⅱ (roman numeral)"],
    "ⅲ": ["ⅲ (roman numeral)"],
    "ⅳ": ["ⅳ (roman numeral)"],
    "ⅴ": ["ⅴ (roman numeral)"],
    "ⅵ": ["ⅵ (roman numeral)"],
    "ⅶ": ["ⅶ (roman numeral)"],
    "ⅷ": ["ⅷ (roman numeral)"],
    "ⅸ": ["ⅸ (roman numeral)"],
    "ⅹ": ["ⅹ (roman numeral)"],
    "\"": ["a\"b"],
    "`": ["a`b"],
    "¥": ["a¥b"],
    "†": ["a†b"],
    "‡": ["a‡b"],
    "•": ["a•b"],
    "‣": ["a‣b"],
    "◦": ["a◦b"],
    "‱": ["a‱b"],
    "№": ["a№b"],
    "℗": ["a℗b"],
    "©": ["a©b"],
    "®": ["a®b"],
    "™": ["a™b"],
}