(()=>{'use strict';const P=new Map(),NS='http://www.w3.org/2000/svg',G=document.querySelector('#planes'),L=document.querySelector('#links'),status=document.querySelector('#status'),echo=document.querySelector('#echo');let mod=null;
const el=(n,a={})=>{const x=document.createElementNS(NS,n);for(const k in a)x.setAttribute(k,a[k]);return x};
function apply(o){if(o.op==='PRESENTIATE')P.set(o.id,{...o,aligned:new Set});else if(o.op==='MOVE'&&P.has(o.id))Object.assign(P.get(o.id),{x:o.x,y:o.y});else if(o.op==='SET_SIZE'&&P.has(o.id))P.get(o.id).r=o.r;else if(o.op==='ROTATE'&&P.has(o.id))P.get(o.id).theta=o.theta;else if(o.op==='ALIGN'){P.get(o.a)?.aligned.add(o.b);P.get(o.b)?.aligned.add(o.a)}else if(o.op==='CONTAIN'&&P.has(o.id))P.get(o.id).parent=o.parent;else if(o.op==='MANIFOLD'){(o.contents||[]).forEach(x=>{if(P.has(x))P.get(x).hidden=true})}else if(o.op==='UNFOLD'){for(const p of P.values())if(p.parent===o.id)p.hidden=false}}
function draw(){G.innerHTML='';L.innerHTML='';for(const p of P.values()){if(p.hidden)continue;if(p.parent&&P.has(p.parent)){const q=P.get(p.parent);L.append(el('line',{x1:p.x,y1:p.y,x2:q.x,y2:q.y,class:'link'}))}for(const b of p.aligned||[]){if(P.has(b)&&p.id<b){const q=P.get(b);L.append(el('line',{x1:p.x,y1:p.y,x2:q.x,y2:q.y,class:'align'}))}}const g=el('g',{class:'plane'+(p.parent?' child':''),transform:'translate('+p.x+' '+p.y+')'});g.append(el('circle',{r:p.r||30}));const t=el('text');t.textContent=p.word;g.append(t);G.append(g)}}
function result(r){(r.ops||[]).forEach(apply);draw();const e=r.echo||{};echo.textContent=(e.arm?e.arm+': ':'')+(e.reason||'');if(r.gap)echo.textContent+=' Definition status: '+r.gap.def}
async function boot(){try{const py=await loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.26.4/full/'});status.textContent='Loading Echo modules…';const man={files:["echo/__init__.py","echo/browser_ksm.py","echo/kernel/__init__.py","echo/kernel/skeleton.py","echo/matrix/__init__.py","echo/matrix/registry.py","echo/canvas/__init__.py","echo/canvas/ks_recess.py","echo/operators/__init__.py","echo/operators/lhea.py"]};for(const f of man.files){const res=await fetch('./'+f);const path='/home/pyodide/'+f;py.FS.mkdirTree(path.split('/').slice(0,-1).join('/'));py.FS.writeFile(path,await res.text())}py.runPython("import sys; sys.path.insert(0,'/home/pyodide')");mod=py.pyimport('echo.browser_ksm');const r=JSON.parse(mod.boot());result(r);const dl=document.querySelector('#words');(r.words||[]).forEach(w=>{const o=document.createElement('option');o.value=w;dl.append(o)});status.textContent='Echo ready · KSM live'}catch(e){status.textContent='Boot error';echo.textContent=e.message||String(e)}}
document.querySelector('#form').addEventListener('submit',ev=>{ev.preventDefault();if(!mod)return;const input=document.querySelector('#word'),w=input.value.trim();if(!w)return;try{result(JSON.parse(mod.presentiate(w)));input.value=''}catch(e){echo.textContent='Runtime error: '+e.message}});
const LESSONS={1:{objective:"Learning, directed study, identification, differentiation, instantiation, designation, and symbolic representation.",words:["study","learn","learning","focus","attention","identify","identification","differentiate","distinction","compare","recognize","instantiate","designation","assign","name","label","symbol","represent","reference","define","classify","category","property","attribute","observe","inspect","detect","select","determine","understand","comprehension","memory","recall","practice","test","question","answer","evidence"]},2:{objective:"Intelligence, information, knowledge, reasoning, inference, concepts, coherence/coherency, articulation, formalization, representation, and evaluation.",words:["intelligence","information","knowledge","data","evidence","fact","belief","uncertainty","reasoning","inference","deduction","induction","abduction","logic","premise","conclusion","observation","perception","recognition","attention","memory","learning","understanding","comprehension","meaning","concept","coherency","coherence","articulation","formalization","abstraction","generalization","classification","comparison","distinction","relation","pattern","structure","representation","interpretation","analysis","synthesis","evaluation","hypothesis","contradiction","consistency","validity","relevance","signal","noise","input","output","communication","language","symbol"]}};
function renderLesson(){const l=LESSONS[document.querySelector('#lessonSelect').value];document.querySelector('#lessonObjective').textContent=l.objective;document.querySelector('#lessonWords').textContent=l.words.join(' · ')}
document.querySelector('#lessonSelect').addEventListener('change',renderLesson);renderLesson();
document.querySelector('#administer').addEventListener('click',()=>{if(!mod)return;const l=LESSONS[document.querySelector('#lessonSelect').value],known=[],gaps=[];for(const w of l.words){try{const r=JSON.parse(mod.presentiate(w));if(r.ok){known.push(w);result(r)}else gaps.push(w)}catch(e){gaps.push(w)}}document.querySelector('#lessonReport').textContent='Administered: '+known.length+' indexed residents · '+gaps.length+' vocabulary gaps'+(gaps.length?': '+gaps.join(', '):'')});

boot();})();